### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by proski** [Bdot42/mfakto#40]
As mentioned in #39, the `0.17pre7` release is misnamed.

The `0.17pre7` tag is clearly a typo. It should be removed and `0.15pre7` created for the same commit. The release should be updated as well.

Another approach would be to adopt semantic version (see https://semver.org/ for details). The next release could be 0.18.0 or 0.20.0 to supersede both 0.15 and 0.17.

In my opinion, `pre`, `rc` and similar adornments add confusion and discourage users from trying the latest version. For instance, Linux kernel use `rc` to indicate a version for testing, but the kernel versions are released often, so most users should be using releases without `rc`. For slower release cycles, the option to wait until the full release is less attractive.

**Comment by brubsby** [comment]
I personally have been adopting one aspect of semver, and releasing mfaktc versions 0.23-beta.<n> as prerelease versions for a bit more clarity. Perhaps we should move to full semver though, and go for 0.23.0-beta.<n> for mfaktc and 0.16.0-beta.<n> for mfakto prerelease versions.

I don't think we should skip 0.16 and 0.17 just because of a superficial typo. As no results were ever reported to the server under this version, as the software itself was still always reporting the version as 0.15pre<something>. Most users are pointed to https://download.mersenne.ca/mfakto to get their releases as the github release has been confusingly incorrect for ~4 years

**Comment by brubsby** [comment]
Also related to this, a version titled 0.15pre8 is being distributed via SRBase, this executable should be hunted down and added as a release under 0.15pre8, and it likely is affected by the barrett15 double precision false negative bug. Otherwise there might be multiple code versions reporting results under 0.15pre8, affecting the ability to discern between the code versions server-side.

**Comment by proski** [comment]
The issue has been addressed in the https://github.com/primesearch/mfakto repository.
